# Generated by Django 3.2 on 2024-09-04 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0002_auto_20240904_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 19, 53, 36, 257941, tzinfo=utc), verbose_name='time bunked'),
        ),
    ]
