# Generated by Django 3.2 on 2024-09-08 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0003_alter_bunk_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time bunked'),
        ),
    ]
