# Generated by Django 3.2 on 2024-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0005_user_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(),
        ),
    ]
