# Generated by Django 3.2 on 2024-09-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_id',
            new_name='auth_user',
        ),
    ]
